### ISSUE TITLE
Support acor to check from group resource member

### ISSUE THREAD

**Issue by samuelbles07** [ankraft/ACME-oneM2M-CSE#114]
Hi,

As specification that quoted below:

> When the originatorID is the resource-ID of a < group > resource which contains < AE > or < remoteCSE > as member, the Hosting CSE of the resource shall check if the originator of the request matches one of the members in the memberIDs attribute of the < group > resource (e.g. by retrieving the < group > resource). If the < group > resource cannot be retrieved or doesn't exist, the request shall be rejected.

Then i see that currently it is not supported. So i create some changes to accommodate it and it works for the purpose. [Please see here](https://github.com/samuelbles07/ACME-oneM2M-CSE/commit/4290411d10838b7f362a35b254485ebe06edc490).

Thanks!

**Comment by ankraft** [comment]
I took your idea and added this to the ACP checks. This also covers now the ACP configurations in he *pvs* attribute.
It is available now in the development version. I hope to make a new release soon.

Thanks for the contributing!
