### ISSUE TITLE
[ASK] Redundant value check on announceUpdatedResource()

### ISSUE THREAD

**Issue by samuelbles07** [ankraft/ACME-oneM2M-CSE#122]
Hi, hope you all well.

I wonder if it's on purpose to do [this](https://github.com/ankraft/ACME-oneM2M-CSE/blob/master/acme/services/AnnouncementManager.py#L430) 

```
announcedCSIs.append(csi)	# build a list of already announced CSIs
remoteRIs.append(csi) 		# build a list of remote RIs
```

`remoteRIs` append csi value too, and doing [non-announced check](https://github.com/ankraft/ACME-oneM2M-CSE/blob/master/acme/services/AnnouncementManager.py#L435) to both list even with the same value.

```
# Check for any non-announced csi in at, and possibly announce them 
	for csi in CSIsFromAnnounceTo:
		if csi not in announcedCSIs and csi not in remoteRIs:
			self.announceResourceToCSI(resource, csi)
```

**Comment by ankraft** [comment]
This really looks like some unnecessary duplicated work here. It could be that this is a left-over from some refactoring in the past. I will need to do some checkings whether this doesn't have some unintended side-effects and then remove it.

Good catch! Thank you for reporting this.

**Comment by ankraft** [comment]
Fixed in development version. Will be available with next release then.
