### ISSUE TITLE
Wrong attribute policy for uds

### ISSUE THREAD

**Issue by samuelbles07** [ankraft/ACME-oneM2M-CSE#140]
Hi,

Based on TS-0004, `uds` attribute should be able to be updated. But on [attributePolicies.ap](https://github.com/ankraft/ACME-oneM2M-CSE/blob/master/init/attributePolicies.ap#L3405) it is set to **NP** which it should be **O**.

![Screen Shot 2024-03-05 at 23 38 45](https://github.com/ankraft/ACME-oneM2M-CSE/assets/18721002/c7de6719-76b1-43d3-b8ce-06e37dcebad8)

Thank you!

**Comment by ankraft** [comment]
Thanks a lot! Good catch! 
Would you like to create a PR, or would it be sufficient if I make the change in the development branch? It would then included when I make the next release (planned in a few weeks).

**Comment by samuelbles07** [comment]
Okay done #141

**Comment by ankraft** [comment]
Thanks a lot!
