### ISSUE TITLE
?sqi=true&rcn=10&smf=PREFIX... vs  ?fu=1&smf=PREFIX...

### ISSUE THREAD

**Issue by alexe100** [ankraft/ACME-oneM2M-CSE#164]
Hello,
I have been dealing with the ACME Semantic Descriptor support and now I am blocked on the way to get parent resources from a smf discovery.

I have created a AE with a descriptor with RDF...

When I execute a discover like this:    ...?sqi=true&rcn=10&smf=PREFIX... I get the right result:

{"m2m:qres": "{\"results\": {\"bindings\": [{\"device\": {\"type\": \"uri\", \"value\": \"http://example.com/devices/1\"}}]}, \"head\": {\"vars\": [\"device\"]}}"}

but when I execute the same but now using:     ?fu=1&smf=PREFIX...  to get parent resources (e.g. AE) I get:

{"m2m:uril": []}

Do ACME supports the returning of parent resources when the smf query hits?

Thank you
Alex

**Comment by alexe100** [comment]
For this little test I have just one AE, with one cont and a SD both suns of AE.
In the discovery operation I am passing path to the parent AE, e.g. 

'http://192.168.122.1:8081/cse-mn/CSensorIndoorTemperature?fu=1&smf=PREFIX+

I also tried to pass 'http://192.168.122.1:8081/cse-mn?fu=1&smf=PREFIX+  but the return is the same:
{"m2m:uril": []}

Does ACME supports discover based on smf?

**Comment by ankraft** [comment]
Yes, it does. The issue is that with `fu=1` the CSE does first a oneM2M "discovery" operation, which means a list of URI's of the child resources of your target, here the AE. In the next step, the CSE applies the semantic filtering on that list.  In your example the list contains Uris to the cnt and smd of the AE. Semantic filtering is working on child (!) resources of the target resources that are SMD resources. But since there are none, the result is empty.

Roughly: 

Resource tree:

```
AE
  + cnt
  + smd
```

1. step: discovery: list = [ AE/cnt, AE/smd] 
2. step: semantic filter:
     1. look for  AE/cnt/smd -> none
     2. look for AE/smd/smd -> none
3. result: list = [ ]

**Comment by alexe100** [comment]
I am following document TR-0045... That is why I created the SD inside AE
I have just created the same SD but now inside cont and discovery returns {"m2m:uril": []}

**Comment by alexe100** [comment]
Ok.
But as you wrote the algorithm used to answer discover operations:


    step: discovery: list = [ AE/cnt, AE/smd]
    step: semantic filter:
        look for AE/cnt/smd -> none
        look for AE/smd/smd -> none
    result: list = [ ]


I thought that if I created the SD inside the container that it would be returned by executing a successful SPARQL query, but it is not. Please could you present the ordered steps to create the oneM2M resources including SD to be possible to return the parent of a (successful processed) SD? 

Thank you

**Comment by alexe100** [comment]
In fact I have thought once to create a oneM2M implementation as you did and as you are doing, because the majority of open source implementations have serious dependencies problems and... etc. Except ACME of course. I am dealing with standardization and have chosen oneM2M and I have just adopted ACME which seems to be a good piece of software and well written. Congratulations! So it is expected that in future days I will post new questions here when things get "blur". :-)

Great link and very useful!

Thanks once again.
Alex

**Comment by ankraft** [comment]
Thank you very much for your kind words!

You are saying you are dealing with standardization. Are your planning to attend the oneM2M standardization meetings? We, the oneM2M standardization group, are just meeting this week at ETSI in France.

Please keep the questions coming. Perhaps also consider to ask them on StackOverflow (if they are general oneM2M question). Then the discussion will help a broader audience.

**Comment by alexe100** [comment]
I am very interested in interoperability and in oneM2M in particular. 
Can anyone attend oneM2M meetings? Do you belong to the oneM2M board? 
Is it possible to attend via online? (no possibility to go to France). If so I would like to attend.

**Comment by ankraft** [comment]
Could you try contact me on the discord channel? I'd like to introduce you to the technical plenary chair to arrange things

**Comment by alexe100** [comment]
When I try to access https://discord.com/invite/6ryMHQC2Uj I have been getting "Invite Invalid"...
You said that meeting is in this week but when? Friday, Saturday, Sunday? I am going to talk about this with my R. Coordinator and probably he is also interested (if available) to attend the meeting. 
Here is a (secondary) email for exchanging details: acptab630@gmail.com

**Comment by ankraft** [comment]
> When I try to access https://discord.com/invite/6ryMHQC2Uj I have been getting "Invite Invalid"...

For me the link works. It seems that sometimes discord has troubles with the verification :(
