### ISSUE TITLE
incorrect rcn response types

### ISSUE THREAD

**Issue by Spongman** [ankraft/ACME-oneM2M-CSE#30]
i believe the handling of rcn response types is wrong.

for example, ts-0004 table 7.5.2-2 lists `R/6` as returning an `m2m:resourceRefList`, whereas this code returns an `m2m:URIList`.

also, this code doesn't return anything for `rcn=6` unless `fu=1` is passed.

**Comment by ankraft** [comment]
For the first part: you are right, this should be a m2M:resourceRefList.

For the second part (fu=2): no this applies to discovery operations only. See note 2 below that table.

**Comment by ankraft** [comment]
A fix is now available on the [development branch](https://github.com/ankraft/ACME-oneM2M-CSE/tree/development).

**Comment by Spongman** [comment]
i get the following trying to run the dev branch:
````
ACME 0.4.0-pre - An open source CSE Middleware for Education
Configuration Error: Wrong format for [cse.remote]:cseID: in-cse
````

**Comment by Spongman** [comment]
funnily enough, i think the eclipse om2m implemtnation also has this issue.

**Comment by ankraft** [comment]
It could be. A new version is in review though. Perhaps this might be solved then.

**Comment by Spongman** [comment]
shouldn't `/id-in?fu=1` return a `URLList`?

i'm _really_ confused :(

**Comment by ankraft** [comment]
I need to check. Stay tuned.

**Comment by Spongman** [comment]
here's a matrix of responses (from the current development branch code) for various different combinations of `fu=`, `rcn=` and `drt=` flags. can you please double-check that these are all correct?
https://docs.google.com/spreadsheets/d/1_eQOpghaDnWzYZ672pvBS77yFupSVEuNORSO_qin2mY

**Comment by ankraft** [comment]
Please note that some of the rcn types are rather new in the unreleased oneM2M spec. Also some changed, so that the test cases need to be developed for them as well. Also, this CSE doesn't implement all rcn types yet.
