### ISSUE TITLE
dynamic updates interrupt UI

### ISSUE THREAD

**Issue by Spongman** [ankraft/ACME-oneM2M-CSE#40]
development:

it looks like there's some kind of dynamic updates going on which causes the 'Resource ID/URL' input box to get overwritten, in the middle of typing...

**Comment by Spongman** [comment]
yeah, if you click on the root node in the tree on the left, then type in a rest url like '/id-in/?fu=1' and hit 'send', then it does a form post, then a series of requests that cause the selection in the tree to change and the url in the form on the right to get overwritten.

**Comment by Spongman** [comment]
looks like this is the issue, it's causing the selection to jump around and mess everything up:
````
    if (node != root) {
      if (node.wasExpanded) {
        node.setExpanded(true)
        //clickOnNode(null, node)
        expandNode(node)
      } else {
        //clickOnNode(null, node)
        node.setExpanded(false)
      }
    } else { // Display the root node expanded and show attributes etc
      expandNode(root)
      root.setSelected(true)
      //clickOnNode(null, root)
    }
````

**Comment by ankraft** [comment]
Thanks for the detective works. Another change that went wrong today.
