### ISSUE TITLE
'limit' and 'direct child resource'

### ISSUE THREAD

**Issue by Spongman** [ankraft/ACME-oneM2M-CSE#42]
TS-0001, 8.1.2: 
> The offset, maximum number/size and maximum level shall be specified in **Filter Criteria** as _offset_, _limit_, and _level_ condition, respectively, by the Originator. Processing of direct child resources, size limitations, maximum nesting level, and offset for the starting of direct child resource processing of **the attributes+child-resources** option shall apply to this option as well.

I'm not really sure what "direct child resources" means here, as it's never clearly defined in the spec, except maybe in TS-0004:

> The level element of the **Filter Criteria** parameter does not represent a filter condition. It imposes a maximum limit on the depth of child resources in the resource tree that the Hosting CSE shall perform a Retrieve request upon. The _**level**_ of 1 shall indicate the direct child resources."

However, the code here doesn't seem to act consistently wrt the _limit_ parameter, for example the query `/id-in?fu=1&rcn=8&ty=52&ty=28&lim=2` returns:
````
{
    "acme:csest": [
        {
            "rn": "statistics",
            "cnd": "acme.statistics",
            "acpi": [
                "acp1028273287565921797"
            ],
            "mni": 10,
            "rmRes": 634,
            "crRes": 653,
            "htRet": 1191,
            "htCre": 6,
            "htUpd": 644,
            "htDel": 0,
            "lgErr": 4,
            "lgWrn": 1290,
            "cseSU": "20200610T032059,778926",
            "cseUT": "1:46:01",
            "ctRes": 19,
            "ri": "csest2319516495356652035",
            "ct": "20200609T200338,971435",
            "lt": "20200609T220700,932786",
            "et": "20210609T200338,971524",
            "pi": "CX677vJit2W",
            "st": 651,
            "ty": 28,
            "cs": 375,
            "cr": "CX677vJit2W",
            "cni": 10,
            "acme:csest": [
                {
                    "rn": "statistics_642",
                    "ct": "20200609T220527,280788",
                    "et": "20210609T200338,971524",
                    "cs": 375,
                    "or": "CX677vJit2W",
                    "rmRes": 625,
                    "crRes": 644,
                    "htRet": 1191,
                    "htCre": 6,
                    "htUpd": 635,
                    "htDel": 0,
                    "lgErr": 4,
                    "lgWrn": 1272,
                    "cseSU": "20200610T032059,778926",
                    "cseUT": "1:44:27",
                    "ctRes": 19,
                    "acpi": [
                        "acp1028273287565921797"
                    ],
                    "ri": "csest4365045063646020904",
                    "lt": "20200609T220527,296168",
                    "pi": "csest2319516495356652035",
                    "st": 0,
                    "ty": 52
                }
            ]
        }
    ]
}
````

the `lim=2` parameter here seems to be affecting the **total** number of children returned, not the number of "direct child resources" 

the weird thing is that if i query `/id-in?fu=1&rcn=8&ty=52&ty=28&lvl=1` instead i get no results, so it's not clear what the `lvl` parameter is applying to here, or what the "direct child resource" phrase really means.

**Comment by ankraft** [comment]
Thanks for the comment. This still needs some testing.

**Comment by Spongman** [comment]
ok, so if this is correct:

> ok, so it sounds like ofst skips over the direct children of the addressed resource that contain matching resources, regardless of whether or not those direct children themselves match.

that means it's impossible to 'page' through children
