### ISSUE TITLE
is it possible to run the webui and the CSE on different machines?

### ISSUE THREAD

**Issue by Spongman** [ankraft/ACME-oneM2M-CSE#73]
is it possible to run the webui and the CSE on different machines?

**Comment by ankraft** [comment]
The web UI can be accessed form another machine. For this the CSE's http server must bind to a public interface. The default is 127.0.0.1 (local loopback). You can change this in the configuration file in the [server.http] section.

If you mean whether the web UI can be served from another machine: no, not yet, but we have a task in the backlog to move  the web UI part to a separate application.

**Comment by ankraft** [comment]
Update: You can now run the web UI independently from the CSE. In the "development" branch, go to the directory "webui" and run the application webUI.py . You need to specify the host and port of the CSE you want to connect to on the command line; see "-h" command line option for all the configuration options.
