### ISSUE TITLE
"Syslog" module not found error

### ISSUE THREAD

**Issue by shubham000000** [ankraft/ACME-oneM2M-CSE#87]
One or more required packages (Syslog) could not be found.

**Comment by shubham000000** [comment]
Thank you, _syslog_ module issue is fixed, but now not able to access UI on webpage, it says 

{"m2m:dbg": "Release Version Indicator is missing in request, falling back to RVI='1'. But Release Version '1' is not supported. Use RVI with one of ['2a', '3', '4']."}

**Comment by shubham000000** [comment]
Thank you, i was trying to access the UI using _127.0.0.1:8080/webpage_ instead of _127.0.0.1:8080_.

I can access the UI on 127.0.0.1:8080.

Thank you very much, it is working perfectly fine.

**Comment by ankraft** [comment]
Great! Good to hear.

BTW, you can change the end point for the web UI setting or adding the following setting to the *acme.ini* configuration file:

    [cse.webui]
    ; Root path of the web UI. Default: /webui
    root=/webui

**Comment by shubham000000** [comment]
Yes, thank you very much once again.
