### ISSUE TITLE
notificationserver.py error (https://github.com/oneM2M/onem2m-jupyter-notebooks/tree/master)

### ISSUE THREAD

**Issue by shubham000000** [ankraft/ACME-oneM2M-CSE#88]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\Desktop\onem2m-jupyter-notebooks\tools\NotificationServer\NotificationServer.py:264, in <module>
    261 def exitAll() -> None:
    262 	os.kill(os.getpid(), signal.SIGUSR1)
--> 264 signal.signal(signal.SIGUSR1, exitSignalHandler)
    266 if __name__ == '__main__':
    267 	console = Console()

AttributeError: module 'signal' has no attribute 'SIGUSR1'

**Comment by ankraft** [comment]
Thank you for reporting this error. I assume that this happens under Windows. Unfortunately, SIGUSR1 is not available on Windows.  
I replaced it with SIGTERM in the development branch and in the [oneM2M notebooks](https://github.com/ankraft/onem2m-jupyter-notebooks), and I hope this works now. If you could be so kind to test it under Windows and confirm that I does work correctly, I will integrate it in the master branch as well.

**Comment by shubham000000** [comment]
> Thank you for reporting this error. I assume that this happens under Windows. Unfortunately, SIGUSR1 is not available on Windows. I replaced it with SIGTERM in the development branch and in the [oneM2M notebooks](https://github.com/ankraft/onem2m-jupyter-notebooks), and I hope this works now. If you could be so kind to test it under Windows and confirm that I does work correctly, I will integrate it in the master branch as well.

Thank you very much, the notificationserver error is solved, also, could you please update the syslog error in the notebook files. Although I updated in the downloaded files but it will be useful for others if you update the syslog error in the notebook files.

Wholeheartedly, thank you for kind support.

**Comment by ankraft** [comment]
Thank you very much for reporting this. My access to MS Windows-based systems is very limited, therefore I am thankful for your help and patience.
Also thank you for your suggestion. I will update the notebooks in the next days.
