### ISSUE TITLE
Incorrect HTTP Response Code for responseTimeout

### ISSUE THREAD

**Issue by ExpandingDev** [ankraft/ACME-oneM2M-CSE#94]
According to TS-0009, table 6.3.2-1, the HTTP status response code for the `4008 REQUEST_TIMEOUT` status should be `504 GATEWAY_TIMEOUT`.

Modifying [this line](https://github.com/ankraft/ACME-oneM2M-CSE/blob/58998491767b41c49ee9bed6aab9e868ffe9641f/acme/etc/Types.py#L601) to be `HTTPStatus.GATEWAY_TIMEOUT` will fix this.

**Comment by ankraft** [comment]
Good catch. Thank you.
